version: "3"

services:
  modus-front:
    build: ./front
    command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build
    environment:
      - NODE_ENV=production
  modus-back:
    build: ./back
    command: sh -c "npm run build && npm run prod"
    expose:
      - 4000
    environment:
      - NODE_ENV=production
      - SERVER_PORT=4000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.9
  nginx:
    image: nginx:1.21.3
    depends_on:
      - modus-back
      - modus-front
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
volumes:
  web-client-build: