services:
    modus-front:
        build: ./front
        ports:  
            -   3000:3000
        volumes:
            -   ./front/src/:/app/src
    modus-back:
        build: ./back
        ports:
            -   4000:4000 
        command: npm start
        links:
        -   mongodb:data
        volumes:
            -   ./back/src/:/app/src
    mongodb: 
        image: mongo
        container_name: mongo
        restart: always
        volumes:
            - ./data:/data/db
