name: docker-ci 
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./modus-front
          file: ./front/Dockerfile
          push: true,
          # Une des possibilités à essayer serait de créer un repo DockerHub contenant les 3 imagesn et donc le renseigner ici à la place de l'image front
          tags: datebayo350/modus-front:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}